version: '3.4'

services:
  udemyreact:
    image: udemyreact
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
